apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-debug-flow.fullname" . }}
  labels:
    {{- include "kafka-debug-flow.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
